name: site_aidat_management
description: Multi-tenant site & dues management mobile app built with Flutter and Clean Architecture.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.4.0
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  collection: ^1.18.0
  intl: ^0.18.1
  syncfusion_flutter_pdf: ^24.1.41
  firebase_core: ^2.25.4
  dartz: ^0.10.1
  firebase_messaging: ^14.7.10
  file_picker: ^6.1.1
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
