import 'dart:math';

class FortuneVault {
  static final List<String> _fortunes = [
    'Kalbindeki en derin dilek hiç ummadığın bir anda gerçek olacak. Gece yarısı duyacağın bir haber yeni kapılar açacak.',
    'Telve çizgileri, uzun zamandır ertelediğin hayalinin artık eyleme geçmesini söylüyor. Cesaret ettiğin anda destek gelecek.',
    'Gökyüzündeki ışıklar sana eski bir dosttan mesaj taşıyor. Bu mesaj içindeki düğümü çözecek.',
    'Yakında yapacağın bir yolculuk, hayatındaki yönü değiştirecek yeni biriyle karşılaştıracak seni.',
    'Fincandaki halkalar, geçmişten gelen borçların kapanacağını müjdeliyor. Rahat bir nefes alacaksın.',
    'Telve izleri, evinde küçük ama huzur dolu bir kutlama olduğunu fısıldıyor. Gelen misafir sana sürpriz getirecek.',
    'Bir proje ya da fikir için günlerdir aradığın ilham, sabah kahveni içerken zihnine düşecek.',
    'Gözlerini kapadığında gördüğün renkler sana yeni bir başlangıcın kapıda olduğunu anlatıyor.',
    'Uzun zamandır görmek istediğin şehir seni çağırıyor. Orada kaybolan bir parçanı bulacaksın.',
    'Geceleri duyduğun rüzgar, kalbindeki korkuları alıp götürüyor. Cesur bir adım, zincirlerini kıracak.',
    'Telve desenleri, kitap sayfaları arasında saklı bir sırrı açığa çıkaracağını söylüyor.',
    'Uzakta bir yıldız senin için parıldıyor. Onun ışığı yeni bir iş fırsatını yanında getirecek.',
    'Fincanın kenarındaki çizgi, hayatına yeni girecek kişinin sana umut vereceğini anlatıyor.',
    'Yakında alacağın bir davet seni uzun süredir beklediğin bir haberle karşılaştıracak.',
    'Ruhunun aradığı huzur, deniz kıyısında saklı. Dalga seslerine kulak verirsen kalbin dinginleşecek.',
    'Kahve kokusu, evine bolluk ve bereket getirecek bir haberi çağırıyor.',
    'Fincandaki spiral, geçmişte yarım kalan bir işi tamamlayacağını haber veriyor.',
    'Telve izleri, uzun zamandır beklediğin kişinin adını kalbine fısıldıyor.',
    'Yakın çevrenden birinin desteğiyle yeni bir girişime başlayacaksın.',
    'Gökyüzüne baktığında göreceğin yıldız, sana yepyeni bir tutkuyu işaret edecek.',
    'Telve çizgileri bir yol işareti gibi. Uzun yola çıkmadan önce kalbinin sesini dinle.',
    'Bu hafta duyacağın bir şarkı, karar veremediğin konuda rehber olacak.',
    'Fincandaki parlak izler, başarıya giden yolunun aydınlandığını anlatıyor.',
    'Kader, sana beklenmedik bir ortaklık sunuyor. Bu ortaklık yeni ufuklar açacak.',
    'Telve, kalbindeki kırgınlığın iyileşeceğini söylüyor. Affetmek sana güç verecek.',
    'Yakın zamanda bir mektup alacaksın. Bu mektup geçmişle hesaplaşmanı sağlayacak.',
    'Gölgeler, içindeki korkuların yüzeye çıkacağını ama onları dönüştürecek güce sahip olduğunu anlatıyor.',
    'İçinde tuttuğun sır paylaşılmak istiyor. Doğru kişiyi seçtiğinde sırtın hafifleyecek.',
    'Kahve kupanın ortasındaki şekil, sana ilham verecek bir rüyayı işaret ediyor.',
    'Telve desenlerinde beliren kuş, güzel haberlerin yolda olduğunu müjdeliyor.',
    'Yakın zamanda tanışacağın biri, hayatına sihirli bir dokunuş yapacak.',
    'Fincanın kıyısındaki çizgi, sana yeni bir eğitimin kapısını aralıyor.',
    'Kalbindeki sorulara cevap olacak kişi senden çok uzakta değil. Gözlerini açman yeterli.',
    'Telve izleri, geçmişte aldığın bir kararın arkasında durman gerektiğini söylüyor.',
    'Yakında yaşayacağın bir tesadüf, kaderin sana göz kırpması olacak.',
    'Fincandaki dağ silueti, zirveye ulaşmak için son bir adımın kaldığını anlatıyor.',
    'Bir gece ansızın çalan telefon, hayatına yeni bir soluk getirecek.',
    'Telve çizgileri, unutmak istediğin anılara veda etmene yardım edecek.',
    'Yakın zamanda hissedeceğin güçlü bir sezgi, seni doğru karara götürecek.',
    'Fincanın içinde beliren yollar, iki seçenek arasında kalacağını gösteriyor. Kalbini dinle.',
    'Telve, seni bekleyen sıcak bir karşılamayı haber veriyor.',
    'Bu hafta göreceğin bir rüya, gerçek hayatta karşına çıkacak bir işaret taşıyor.',
    'Fincanındaki ışık, küçük bir iyiliğin büyük mutluluk getireceğini söylüyor.',
    'Yakında, ruhunun ihtiyaç duyduğu kişi yanında beliriverecek.',
    'Telve çizgileri, kalbinin ritmini duyan biriyle tanışacağını anlatıyor.',
    'Yakında bir hediye alacaksın; bu hediye geçmişle bağlarını onaracak.',
    'Fincandaki gölgeler, planlarının olgunlaştığını ve hayata geçmek istediğini fısıldıyor.',
    'Uzun zamandır aradığın ilham kaynağı, hiç beklemediğin bir yüzün bakışlarında saklı.',
    'Kahve kokusu ile birlikte gelen fısıltılar, yeni bir maceranın habercisi.',
    'Telve izlerinde beliren köprü, uzak diyarlarda kurulacak bir dostluğa işaret ediyor.',
    'Yakın zamanda bir sır açığa çıkacak ve bu sır sana yeni bir bakış açısı kazandıracak.',
    'Fincanın içindeki spiral, hayatının bir döngüsünün tamamlandığını haber veriyor.',
    'Telve çizgileri, yazacağın bir mesajın çok şeyi değiştireceğini gösteriyor.',
    'Yakın zamanda duyacağın kahkahalar, kalbindeki yükü hafifletecek.',
    'Fincandaki yıldız, başarının artık görünür olduğunu anlatıyor.',
    'Telve izleri, beklediğin haberin güzel sonuçlanacağını fısıldıyor.',
    'Yakında, kalbindeki kırgınlığı şefkatle sarmalayacak biriyle karşılaşacaksın.',
    'Fincandaki dalga, ufkunu genişletecek bir seyahatin kapıda olduğunu haber veriyor.',
    'Telve çizgileri sana, kalbini ısıtacak yeni bir hobi öneriyor.',
    'Yakın zamanda göreceğin bir işaret, sana geleceğin yönünü gösterecek.',
    'Fincandaki çiçek, evine neşe getirecek bir misafiri işaret ediyor.',
    'Telve desenlerinde beliren bir anahtar, kilitli kalmış bir konunun açılacağını söylüyor.',
    'Yakın zamanda katılacağın bir etkinlik, hayatına yeni bir rota çizecek.',
    'Fincandaki kuyruklu yıldız, dileklerinin sıra sıra gerçekleşeceğini anlatıyor.',
    'Telve izleri, beklenmedik bir zamanda alacağın desteği haber veriyor.',
    'Yakında kalbini ısıtacak bir sürpriz kapını çalacak.',
    'Fincandaki yol, karşına çıkacak iki fırsattan parlak olanı seçeceğini söylüyor.',
    'Telve desenlerinde beliren kırlangıç, baharın seninle birlikte doğacağını işaret ediyor.',
    'Yakın zamanda izleyeceğin bir film, hayatına yeni bir perspektif katacak.',
    'Fincandaki ışık demeti, şansının açılacağını müjdeliyor.',
    'Telve izleri, yeni bir dil veya beceri öğrenmek için doğru zamanda olduğunu söylüyor.',
    'Yakında alacağın bir haber, uzun süredir beklediğin kapının aralandığını gösterecek.',
    'Fincanın ortasında beliren kıvılcım, kalbindeki yaratıcı ateşi körüklüyor.',
    'Telve çizgileri, geçmişle barışıp geleceğe güvenle bakacağını anlatıyor.',
    'Yakın zamanda bir davette karşılaşacağın kişi, kalbindeki sorulara yanıt verecek.',
    'Fincandaki çift çizgi, hayatına girecek uyumlu bir ortaklığı işaret ediyor.',
    'Telve desenlerinde beliren gemi, ufka doğru açılacağın bir yolculuğu haber veriyor.',
    'Yakında duygusal bir konuşma yapacaksın; bu konuşma ilişkilerini güçlendirecek.',
    'Fincandaki çember, korunduğunu ve güvende olduğunu anlatıyor.',
    'Telve izleri, uzun zamandır beklettiğin sanat yönünü ortaya çıkarmak istediğini söylüyor.',
    'Yakında bir deftere dökeceğin kelimeler, ruhunu rahatlatacak.',
    'Fincandaki kıvrımlar, kalbindeki sırların artık paylaşılmak istediğini anlatıyor.',
    'Telve çizgileri, hayatında yeni bir ritme geçeceğini fısıldıyor.',
    'Yakın zamanda duyacağın bir anı, sana güç verecek.',
    'Fincandaki bulut, zihnini dolduran kaygıların dağılacağını haber veriyor.',
    'Telve izleri, kalbindeki çocukluğun sesini duymanı istiyor.',
    'Yakın zamanda yeni bir kitapla tanışacaksın; bu kitap sana ışık olacak.',
    'Fincandaki taş silueti, sağlam bir temele oturan bir karar vereceğini söylüyor.',
    'Telve desenlerinde beliren kalp, aşkının karşılık bulacağını müjdeliyor.',
    'Yakın zamanda kalbin hızlanacak; yeni heyecanlar kapıda.',
    'Fincandaki yol ayrımı, sezgilerini takip ettiğinde doğru yola çıkacağını anlatıyor.',
    'Telve çizgileri, hayatına sihirli bir dokunuş yapacak kişiyi çağırıyor.',
    'Yakın zamanda alacağın bir iltifat, özgüvenini tazeleyecek.',
    'Fincandaki sonsuzluk işareti, bağlılıklarının güçlendiğini gösteriyor.',
    'Telve izleri, kalbine huzur getirecek bir müjdeli haberi fısıldıyor.',
    'Yakında bir sırdaşın olacak; ona güvendiğinde içindeki yük hafifleyecek.',
    'Fincandaki ay, gece vakti alacağın ilhamı anlatıyor.',
    'Telve desenlerinde beliren ok, hedefini bulacağını söylüyor.',
    'Yakın zamanda bir kapı kapanacak ama onun ardında saklı fırsatı göreceksin.',
    'Fincandaki dalgalar, kalbinin ritmine uyacak bir melodiye işaret ediyor.',
    'Telve çizgileri, ailenle paylaşacağın sevindirici bir haber olduğunu anlatıyor.',
    'Yakında göreceğin bir yıldız kayması, dileğinin gerçekleşeceğine işaret.',
    'Fincandaki kanatlar, özgürlüğe doğru yol aldığını gösteriyor.',
    'Telve izleri, yeni tanışacağın biriyle kısa sürede yakınlaşacağını söylüyor.',
    'Yakın zamanda yeni bir koleksiyon yapmaya başlayacaksın; bu seni mutlu edecek.',
    'Fincandaki köprü, kırgın olduğun biriyle arandaki bağı onaracağını anlatıyor.',
    'Telve çizgileri, kalbindeki rüyanın peşinden gitmeni istiyor.',
    'Yakın zamanda duyacağın bir fısıltı, sana saklı bilgiyi verecek.',
    'Fincandaki kıvılcım, yaratıcılığının yükseldiğini haber veriyor.',
    'Telve izleri, beklenmedik anda gelen bir misafiri müjdeliyor.',
    'Yakın zamanda kalbini hızlandıracak bir gelişme yaşayacaksın.',
    'Fincandaki yıldırım, ani ama güzel bir değişime işaret ediyor.',
    'Telve çizgileri, evinde yeni bir düzen kuracağını anlatıyor.',
    'Yakın zamanda alacağın bir haberle uzun zamandır beklediğin haber birleşecek.',
    'Fincandaki saat, zamanlamanın artık sana çalıştığını söylüyor.',
    'Telve izleri, kalbinde sakladığın duanın kabul edileceğini fısıldıyor.',
    'Yakında rüzgarın yön değiştirdiğini hissedeceksin; bunu fırsata dönüştür.',
    'Fincandaki kıvrımlar, yollarının yeniden kesişeceği kişiyi işaret ediyor.',
    'Telve desenlerinde beliren taç, hak ettiğin değeri almaya başladığını gösteriyor.',
    'Yakın zamanda sakladığın fikir açığa çıkacak ve alkış toplayacak.',
    'Fincandaki kapı, beklediğin teklifin geleceğini haber veriyor.',
    'Telve izleri, kalbindeki sevginin büyüdüğünü anlatıyor.',
    'Yakında göreceğin bir tablo, ruhuna dokunacak bir hikayeyi açığa çıkaracak.',
    'Fincandaki kıvrımlar, geçmişten gelen bir hediyeyi işaret ediyor.',
    'Telve desenlerinde beliren dal, köklerine olan bağlılığını güçlendirecek.',
    'Yakın zamanda beklemediğin bir övgü, yolunu aydınlatacak.',
    'Fincandaki ışık halkası, korunduğunu ve şanslı olduğunu gösteriyor.',
    'Telve izleri, kalbinin fısıldadığı melodiyi takip etmeni söylüyor.',
    'Yakın zamanda bir dileğin gerçekleşeceği haberini alacaksın.',
    'Fincandaki nehir, hayatına akacak yeni enerjiyi müjdeliyor.',
    'Telve çizgileri, içindeki liderin ortaya çıkmak istediğini anlatıyor.',
    'Yakında bir rüya, sana gizli yolu gösterecek.',
    'Fincandaki güneş, yeni bir başlangıcın sıcaklığını getiriyor.',
    'Telve izleri, beklediğin sevgiyi kalbine taşıyacak.',
    'Yakın zamanda duyacağın bir müzik, unutmak istediğin bir anıyı iyileştirecek.',
  ];

  static String pickFortune({int? seed}) {
    final rng = seed != null ? Random(seed) : Random();
    return _fortunes[rng.nextInt(_fortunes.length)];
  }
}
